services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${NAME_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports: 
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=${NAME_DB};Username=${DB_USER};Password=${DB_PASSWORD};
      - ASPNETCORE_ENVIRONMENT=Development
      - JWT__KEY=${JWT_KEY}

volumes:
  postgres_data: